# Generated by Django 4.1.1 on 2022-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangas',
            name='date',
        ),
        migrations.AlterField(
            model_name='mangas',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manga'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review'),
        ),
    ]
