# Generated by Django 4.1.1 on 2022-09-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_mangas_date_alter_mangas_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='date',
        ),
    ]
