# Generated by Django 4.1.1 on 2022-09-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'ordering': ['name'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contactprofile',
            options={'ordering': ['name'], 'verbose_name': 'Contact Profile', 'verbose_name_plural': 'Contact Profiles'},
        ),
        migrations.RemoveField(
            model_name='contactprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='contactprofile',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
    ]
