# Generated by Django 4.1.1 on 2022-09-14 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contactprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactProfile',
        ),
    ]
