# Generated by Django 4.1 on 2022-09-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
